name: notification_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  android_intent_plus: ^4.0.1
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_foreground_task: ^6.0.0+1
  flutter_local_notifications: ^15.1.0+1
  flutter_riverpod: ^2.3.6
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
