// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATi8Hn6ktp4zdk5HQYAHTGHz-TezfnZ54',
    appId: '1:894502822742:android:36459c70f6678f84776cf7',
    messagingSenderId: '894502822742',
    projectId: 'remindme-6f6a3',
    storageBucket: 'remindme-6f6a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJUrz8v2URw3AkpS70H13oFeoqC_yRnfI',
    appId: '1:894502822742:ios:9835ff76c6308c1d776cf7',
    messagingSenderId: '894502822742',
    projectId: 'remindme-6f6a3',
    storageBucket: 'remindme-6f6a3.appspot.com',
    androidClientId: '894502822742-s1fp41k0foi7f1nmjtpa70btqto2acrd.apps.googleusercontent.com',
    iosClientId: '894502822742-jad9m7hkvik4buq2r0hrhjgf0qrgos4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationApp',
  );
}
